version: '3.7'
services:
  php:
    build: ./docker/php
    ports:
    - 9000:9000
    volumes:
    - ./src/php_app:/src/php_app

  mysql:
    build: ./docker/mysql
    ports:
    - 3306:3306
    volumes:
    - ./db:/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    build: ./docker/phpmyadmin
    ports:
    - 9001:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
